name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83c6a5eb09c0df74b456d6925e067e0c8568a8c5326d42fb11830f635bcb3773"

[versions]
fabric = "0.18.4"
minecraft = "1.21.6"
