name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f24b78deb93b999292fb0bd2a562c21f72d04c5a2c694897963ef5b816d793e4"

[versions]
fabric = "0.19.2"
minecraft = "1.21.6"
