name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c4d2a97c39e3f7d312a0b4bffdf0d913530efceba7d125346b2441debf830125"

[versions]
fabric = "0.18.4"
minecraft = "1.21.6"
