name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11e6ec49acc60a4b8f2f3cfd709ab38eed83d9365a0bc451fc20812309c80d37"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
