name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a6325e665294c03514aa8e5e0ba45b2585728449110cbdd1fecc69360b2b5463"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
