name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c926f04e851d919391b760fa1f7138b6dbccd743e100eef2ac6b09a22b7fe9d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
