name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c4bbd1dc40443724bd54d055277708f47550796eac6af826e15ba9789439274"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
