name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff8b702c461cdd940deb6925d38cd452a6be9c8df3bceba7d7baa6e8565b928a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.9"
