name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49fac9cc984253249f051dee3d03eb182b38aa97050a328b316bdb55d82ce0ed"

[versions]
fabric = "0.18.4"
minecraft = "1.21.9"
