name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31fbc5de998f441bda5b994366f9e91b1a4625bb7ebc4cc21c0aba518f5537c9"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
