name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d632b1df972bb0eff9bd93f1471fba38d9758682ce5fe217710edc1b5e1757c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
