name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "166ff5daf58726eb827219d0f55d052e2fdbf979737f34ec82a4869046234410"

[versions]
fabric = "0.18.4"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
