name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "139fc6c8317ca15bcacb064068f72500957fa9b3e7d5518fb537c80467c8ea80"

[versions]
fabric = "0.19.2"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
