name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc26e876e00b05929ed8a6f59bc29bcf85c3654d3b16ac5ca6e304a07bc2bba7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
