name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4b46ef7c26daf767f16a82d74c9e0d4e63ce6067ae95ab2fe9ebdba57e15e0a"

[versions]
fabric = "0.18.4"
minecraft = "1.21.5"
