name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbf738d7ed370d1ee752127cc27242fff1c49f981eb0e4ce637d0c2c6695c1ed"

[versions]
fabric = "0.18.4"
minecraft = "1.21.5"
