name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f4de4af67caf7852075e4f0764800f5d7e5b745b9659ca0faa23e4e23a730e96"

[versions]
fabric = "0.19.2"
minecraft = "1.21.5"
