name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a25383ab0fab2b9117a1c8571791cb31a6d5bc2cec331e1c8f821ecddf697ece"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
