name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bb9729fbf96f611aa30171294924a014523f6b241e149cffe5d01ec0dca6aba"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
