name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4290608ed31089bfd5a605521b895ce133ffd592fe2ea142e86e798a602fa26"

[versions]
fabric = "0.19.2"
minecraft = "1.21.8"
