name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d7b12939d048d12ff6828e2584c85d05a0aa466244c26bff2667645b17e647e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
