name = "Net Play MC"
author = "Alfakynz"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69dafb74fc66399fbf640ecb7683f5ee13c05ad9ac3f76f3ec34929302fecf65"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
