name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bb589c6aac0425282eb211111c879fc18b22a1120dae5ae0de753d759714108"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
