name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66a8c9019a18ff599f892a65fa420552b91a0b59cc8c8cf745e38c07fdabf241"

[versions]
fabric = "0.18.4"
minecraft = "1.21.5"
