name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a65c8024f10bf556a3117545ae2416823a2715c0ab06cae473cc6618dcfcdf8b"

[versions]
fabric = "0.19.2"
minecraft = "1.21.5"
