name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da6eaaf984f0a87facb85dda0ae7a897cf58c4a42dec83cbb37bc26693e0777c"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
