name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2932f9911a4218868d360f76578a3e4eeb960f5100168ffda86e23ea30bb7851"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
