name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc15af4924ee071f4e4580e43702f301c29d34add5d16a9ccfc757eb5b432148"

[versions]
fabric = "0.18.4"
minecraft = "1.21.8"
