name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9bd5153c7d1a48db356786e37f37cc06eb3c6036b8e71d2ed534b8d0d6f99e37"

[versions]
fabric = "0.19.2"
minecraft = "1.21.8"
