name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6df4e5c0524180403cc35c86eee1a883bb11bc6b9fc0ffe9a4d55a4bbcc6d3d4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.9"
