name = "Net Play MC"
author = "Alfakynz"
version = "1.4.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5df303734b12dfec6d60491be6728e077e39528b63a0dc7f23d06a880631f937"

[versions]
fabric = "0.19.2"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
