name = "Net Play MC"
author = "Alfakynz"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff256b3ba309db3a7502f022dab5f6ff0d2b87bcbfd31e9c26fe17a0846d85d8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.7"

[options]
acceptable-game-versions = ["1.21.6"]
